version: '2'

services:
  mysql:
    image: mysql:5.7
    command: mysqld --skip-name-resolve
    env_file:
      - ./env/mysql.env
    expose:
     - "3306"

  docker.drupal.base:
    build:
      context: .
    container_name: docker.drupal.base
    links:
      - mysql:mysql
    expose:
     - "80"
    ports:
      - "80:80"
    env_file:
      - ./env/drupal.env
    volumes:
      - ./tests:/app/tests
